language: node_js
node_js:
  - '0.10'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"     # http://stackoverflow.com/a/19416096
  - 'npm install -g bower grunt-cli'
  - 'npm install'
